# Magic method er agee r pore 2ta kore underscore thake.
# egulo ke call korte hoyna , Python interpreter eguloke automatically cll kore...
# __str__(self)  ---->>> This is used, when we try to convert an object in string
